### ISSUE TITLE
maybe use annotationProcessor dependency handler for spring-boot-configuration-processor

### ISSUE THREAD

**Issue by baardhaddeland** [Skatteetaten/aurora-spring-boot-webflux-starter#39]
intellij cannot resolve configuration properties when depending on this starter.
```
Cannot resolve configuration property 'aurora.webflux.header.filter.enabled'
Cannot resolve configuration property 'aurora.webflux.header.webclient.interceptor.enabled'
```

See docs that says use `annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")`
https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#appendix.configuration-metadata.annotation-processor

Believe the problem is here then because its api instead of annotationProcessor
https://github.com/Skatteetaten/aurora-spring-boot-webflux-starter/blob/v1.5.2/aurora-spring-boot-webflux-starter/build.gradle.kts#L25

Suggest you change to?
`annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")`

The jar produced should then contain META-INF/spring-configurational-metadata.json when e.g. using publishToMavenLocal gradle task

**Comment by jarlehansen** [comment]
Fikser på de nye releasene
